export const InventoryItems = [{

    "SlNo.": 1,
    "ItemCode": "IMC-00001",
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemName": "GLOVES NITRILE EXAM  SIZE:LARGE 100\/BOX REF:NGPF7003 SYNGUARD ",
    "GenericName": null,
    "Manufacturer": "SYNGUARD",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 8,
    "UnitsPerPack": 100,
    "SaleUnit": "PCS",
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 50,
    "date": "01-02-2025",
    "type": "Stock Consumption",
    "Spciality": "Mainstore",
    "Barcode": "3546-0210",
    "Qty": 10,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 1,
    "salesunit": "pcs",
    "itemprice" :"300",
    "saftystock" :25,
    "Available":"Available"

},
{
    "SlNo.": 2,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00002",
    "ItemName": " GLOVES NITRILE EXAM SIZE:SMALL 100\/BOX REF:NGPF7001 SYNGUARD ",
    "GenericName": null,
    "Manufacturer": "SYNGUARD",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 8,
    "UnitsPerPack": 100,
    "SaleUnit":30,
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 50,
    "date": "02-02-2025",
    "type": "Stock Consumption",
    "Spciality": "Mainstore",
    "Barcode": "3546-0212",
    "Qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 2,
    "salesunit": "pcs",
    "itemprice" :"400",
    "saftystock" :30,
    "Available":"Available"

},
{
    "SlNo.": 3,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00003",
    "ItemName": "GLOVE PURE SIZE:LARGE 100\/BOX ",
    "GenericName": null,
    "Manufacturer": "PURE",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 15,
    "UnitsPerPack": 100,
    "SaleUnit": "PCS",
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 60,
    "date": "03-02-2025",
    "type": "Stock Consumption",
    "Spciality": "Mainstore",
    "Barcode": "3546-0212",
    "Qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 3,
    "salesunit": "pcs",
    "itemprice" :"500",
    "saftystock" :40,
    "Available":"Available"


},
{
    "SlNo.": 4,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00004",
    "ItemName": "GLOVE DISPOSABLE SANITA SERVU   SIZE:MEDIUM 100\/BOX",
    "GenericName": null,
    "Manufacturer": "SANITA SERVU",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 12,
    "UnitsPerPack": 100,
    "SaleUnit": 15,
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 30,
    "Qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 4,
    "salesunit": "pcs",
    "date": "03-02-2025",
    "itemprice" :"900",
    "saftystock" :20,
    "Available":"Available"

    

},

{
    "SlNo.": 5,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00006",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:6.5 50PAIRS\/BOX REF:1LSPF-1165",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": "PCS",
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 20,
    "Qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 5,
    "salesunit": "pcs",
    "date": "04-02-2025",
    "itemprice" :"100",
    "saftystock" :10,
    "Available":"Available"



},
{
    "SlNo.": 6,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00007",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:7.0 50PAIRS\/BOX REF:1LSPF-1170",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": "PCS",
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 30,    "Qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 6,
    "salesunit": "pcs",
    "date": "06-02-2025",
    "itemprice" :"500",
    "saftystock" :10,
    "Available":"Available"




},
{
    "SlNo.": 7,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00008",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:7.5 50PAIRS\/BOX REF:1LSPF-1175",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": 20,
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 25,
    "date": "07-02-2025",
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 6,
    "salesunit": "pcs",
    "date": "06-02-2025",
    "itemprice" :"400",
    "saftystock" :10,
    "Available":"Available"



},
{
    "SlNo.": 8,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00009",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:8.0 50PAIRS\/BOX REF:1LSPF-1180",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": "PCS",
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 30,
    "UnitPrice": 100,
    "Saleunit": 20,
    "s.no": 6,
    "salesunit": "pcs",
    "date": "06-02-2025",
    "itemprice" :"100",
    "saftystock" :10,
    "Available":"Available"


},

{
    "SlNo.": 9,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00001",
    "ItemName": "48.0230.01 3 PCS Wieder Tongue Depressor 28mm, Fig.1, 14cm",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": "PCS",
    "PurchasePrice": 2030,
    "UnitsPerPack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "itemprice" :"100",
    "saftystock" :10,
    "Available":"Available"


},
{
    "SlNo.": 10,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00002",
    "ItemName": "46.0020.02 3 PCS Thudichum Nasal Speculum (Goldsmith) Fig.2",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": "PCS",
    "PurchasePrice": 2500,
    "UnitsPerPack": 1,
    "SaleUnit": "0",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "itemprice" :"600",
    "saftystock" :10,
    "Available":"not Available"


},
{
    "SlNo.": 11,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00003",
    "ItemName": "46.0020.03 3 PCS Thudichum Nasal Speculum (Goldsmith) Fig.3",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": 1000,
    "PurchasePrice": 1000,
    "UnitPerPack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "itemprice" :"800",
    "saftystock" :30,
    "Available":"Available"


},
{
    "SlNo.": 12,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00004",
    "ItemName": "46.0020.04 3 PCS Thudichum Nasal Speculum (Goldsmith) Fig.4",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": 1500,
    "PurchasePrice": 1500,
    "UnitsPerPack": 1,
    "SaleUnit": "0",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "itemprice" :"800",
    "saftystock" :30,
    "Available":"Available"


},
{
    "SlNo.": 13,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00005",
    "ItemName": "46.0020.05 3 PCS Thudichum Nasal Speculum (Goldsmith) Fig.5",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": 6000,
    "PurchasePrice": 6000,
    "UnitsPerPack": 1,
    "SaleUnit": "1",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "itemprice" :"800",
    "saftystock" :30,
    "Available":"Available"


},
{
    "SlNo.": 14,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00006",
    "ItemName": "44.0250.14 3 PCS Tilley Ear Fcps extra fine serr 14cm",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": 1000,
    "PurchasePrice": 1000,
    "UnitsPerPack": 1,
    "SaleUnit": "0",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "itemprice" :"300",
    "saftystock" :30,
    "Available":"Available"
    

},

{
    "SlNo.": 15,
    "Category": "CONSUMABLES",
    "SubCategory": "OFFICE SUPPLIES",
    "ItemCode": "INMC00001",
    "ItemName": "CD\/DVD Twin marker 1Box \/12pcs",
    "Generic Name": null,
    "Manufacturer": "HILBRO",
    "Purchase Unit": "PCS\/\u4e2a",
    "Purchase Price": 20,
    "UnitsPer Pack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 5,
    "itemprice" :"100",
    "saftystock" :10,
    "Available":"Available"


},
{
    "SlNo.": 16,
    "Category": "CONSUMABLES",
    "SubCategory": "OFFICE SUPPLIES",
    "ItemCode": "INMC00002",
    "ItemName": "Desk Ball Point Pen 0.7MM ",
    "GenericName": null,
    "Manufacturer": null,
    "PurchaseUnit": "PCS\/\u4e2a",
    "PurchasePrice": 10,
    "UnitsPerPack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 5,
    "itemprice" :"300",
    "saftystock" :10,
    "Available":"Available"


},

{
    "SlNo.": 17,
    "Category": "CONSUMABLES",
    "SubCategory": "OFFICE SUPPLIES",
    "ItemCode": "INMC00004",
    "ItemName": "High Lighter Blue 1Box \/10pcs",
    "GenericName": null,
    "Manufacturer": null,
    "PurchaseUnit": "PCS\/\u4e2a",
    "PurchasePrice": 40,
    "UnitsPerPack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 20,
    "itemprice" :"300",
    "saftystock" :10,
    "Available":"Available"


},
{
    "SlNo.": 18,
    "Category": "CONSUMABLES",
    "SubCategory": "OFFICE SUPPLIES",
    "ItemCode": "INMC00005",
    "ItemName": "High Lighter Purple ",
    "GenericName": null,
    "Manufacturer": null,
    "PurchaseUnit": "PCS",
    "PurchasePrice": 10,
    "UnitsPerPack": 0,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Reorderlevel": 20,
    "itemprice" :"800",
    "saftystock" :10,
    "Available":"Available"


},
{
    "SlNo.": 19,
    "Category": "CONSUMABLES",
    "SubCategory": "OFFICE SUPPLIES",
    "ItemCode": "INMC00006",
    "ItemName": "High Lighter Yellow 1Box \/10pcs",
    "GenericName": null,
    "Manufacturer": null,
    "PurchaseUnit": "PCS\/\u4e2a",
    "PurchasePrice": 60,
    "UnitsPerPack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 20,
    "itemprice" :"200",
    "saftystock" :10,
    "Available":"Available"


},
{
    "SlNo.": 20,
    "Category": "CONSUMABLES",
    "SubCategory": "OFFICE SUPPLIES",
    "ItemCode": "INMC00007",
    "ItemName": "High Lighter Turquoise ",
    "GenericName": null,
    "Manufacturer": null,
    "PurchaseUnit": "PCS",
    "PurchasePrice": 30,
    "UnitsPerPack": 0,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 10,
    "itemprice" :"200",
    "saftystock" :20,
    "Available":"Available"


},

]

