export const AdjustStock = [{

    "SlNo.": 1,
    "ItemCode": "IMC-00001",
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemName": "GLOVES NITRILE EXAM  SIZE:LARGE 100\/BOX REF:NGPF7003 SYNGUARD ",
    "GenericName": null,
    "Manufacturer": "SYNGUARD",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 8,
    "UnitsPerPack": 100,
    "itemprice":300,
    "SaleUnit": "PCS",
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 50,
    "date": "01-02-2025",
    "type": "Stock Consumption",
    "Spciality": "Mainstore",
    "Barcode": "3546-0210",
    "qty": 10,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 1,
    "salesunit": "pcs",
    "adjustmentType" :"increase"

    

},
{
    "SlNo.": 2,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00002",
    "ItemName": " GLOVES NITRILE EXAM SIZE:SMALL 100\/BOX REF:NGPF7001 SYNGUARD ",
    "GenericName": null,
    "Manufacturer": "SYNGUARD",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 8,
    "UnitsPerPack": 100,
    "SaleUnit":30,
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 50,
    "date": "02-02-2025",
    "type": "Stock Consumption",
    "Spciality": "Mainstore",
    "Barcode": "3546-0212",
    "qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 2,
    "salesunit": "pcs",
    "itemprice":350,
  


},
{
    "SlNo.": 3,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00003",
    "ItemName": "GLOVE PURE SIZE:LARGE 100\/BOX ",
    "GenericName": null,
    "Manufacturer": "PURE",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 15,
    "UnitsPerPack": 100,
    "SaleUnit": "PCS",
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 60,
    "date": "03-02-2025",
    "type": "Stock Consumption",
    "Spciality": "Mainstore",
    "Barcode": "3546-0212",
    "qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 3,
    "salesunit": "pcs",
    "itemprice":200,
   


},
{
    "itemprice":100,
    "SlNo.": 4,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00004",
    "ItemName": "GLOVE DISPOSABLE SANITA SERVU   SIZE:MEDIUM 100\/BOX",
    "GenericName": null,
    "Manufacturer": "SANITA SERVU",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 12,
    "UnitsPerPack": 100,
    "SaleUnit": 15,
    "SalePrice": 1,
    "Salable": "Y",
    "Reorderlevel": 30,
    "qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 4,
    "salesunit": "pcs",
    "date": "03-02-2025",
    

},

{
    "itemprice":100,
    "SlNo.": 5,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00006",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:6.5 50PAIRS\/BOX REF:1LSPF-1165",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": "PCS",
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 20,
    "qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 5,
    "salesunit": "pcs",
    "date": "04-02-2025",


},
{
    "SlNo.": 6,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00007",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:7.0 50PAIRS\/BOX REF:1LSPF-1170",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": "PCS",
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 30,    "qty": 30,
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 6,
    "salesunit": "pcs",
    "date": "06-02-2025",
    "itemprice":150,



},
{
    "itemprice":150,
    "SlNo.": 7,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00008",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:7.5 50PAIRS\/BOX REF:1LSPF-1175",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": 20,
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 25,
  
    "UnitPrice": 200,
    "Saleunit": 20,
    "s.no": 6,
    "salesunit": "pcs",
    "date": "06-02-2025",
    "qty": 70,


},
{
    "itemprice":120,
    "SlNo.": 8,
    "Category": "CONSUMABLES",
    "SubCategory": "MEDICAL CONSUMABLE",
    "ItemCode": "IMC-00009",
    "ItemName": "GLOVES MEDISMART STERILE SURGICAL  SIZE:8.0 50PAIRS\/BOX REF:1LSPF-1180",
    "GenericName": null,
    "Manufacturer": "MEDISMART",
    "PurchaseUnit": "BOX",
    "PurchasePrice": 40,
    "UnitsPerPack": 50,
    "SaleUnit": "PCS",
    "SalePrice": 2,
    "Salable": "Y",
    "Reorderlevel": 10,
    "UnitPrice": 100,
    "Saleunit": 20,
    "s.no": 6,
    "salesunit": "pcs",
    "date": "06-02-2025",
    "qty": 50,

},

{
    "SlNo.": 9,
    "itemprice":300,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00001",
    "ItemName": "48.0230.01 3 PCS Wieder Tongue Depressor 28mm, Fig.1, 14cm",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": "PCS",
    "PurchasePrice": 2030,
    "UnitsPerPack": 1,
    "SaleUnit": "PCS",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "qty": 20,
    "date": "06-02-2025",



},
{
    "SlNo.": 10,
    "itemprice":50,
    "Category": "CAPITAL ASSETS",
    "SubCategory": "MEDICAL INSTRUMENTS",
    "ItemCode": "FAO-00002",
    "ItemName": "46.0020.02 3 PCS Thudichum Nasal Speculum (Goldsmith) Fig.2",
    "GenericName": null,
    "Manufacturer": "HILBRO",
    "PurchaseUnit": "PCS",
    "PurchasePrice": 2500,
    "UnitsPerPack": 1,
    "SaleUnit": "0",
    "SalePrice": null,
    "Salable": null,
    "Reorderlevel": 0,
    "qty": 10,
    "date": "06-02-2026",


},

]

