import React from 'react'

const MedicalsItems = () => {
    const medicalItems = [
        {
            "Sl No.":1,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00001",
            "Item Name":"GLOVES NITRILE EXAM  SIZE:LARGE 100\/BOX REF:NGPF7003 SYNGUARD ",
            "Generic Name":null,
            "Manufacturer":"SYNGUARD",
            "Purchase Unit":"BOX",
            "Purchase Price":8,
            "Units Per Pack":100,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":2,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00002",
            "Item Name":" GLOVES NITRILE EXAM SIZE:SMALL 100\/BOX REF:NGPF7001 SYNGUARD ",
            "Generic Name":null,
            "Manufacturer":"SYNGUARD",
            "Purchase Unit":"BOX",
            "Purchase Price":8,
            "Units Per Pack":100,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":3,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00003",
            "Item Name":"GLOVE PURE SIZE:LARGE 100\/BOX ",
            "Generic Name":null,
            "Manufacturer":"PURE",
            "Purchase Unit":"BOX",
            "Purchase Price":15,
            "Units Per Pack":100,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":4,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00004",
            "Item Name":"GLOVE DISPOSABLE SANITA SERVU   SIZE:MEDIUM 100\/BOX",
            "Generic Name":null,
            "Manufacturer":"SANITA SERVU",
            "Purchase Unit":"BOX",
            "Purchase Price":12,
            "Units Per Pack":100,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":5,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00005",
            "Item Name":"DISPOSABLE TOURNIQUET 25PCS\/BOX",
            "Generic Name":null,
            "Manufacturer":"MICROTECH",
            "Purchase Unit":"PCS",
            "Purchase Price":0.5,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":6,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00006",
            "Item Name":"GLOVES MEDISMART STERILE SURGICAL  SIZE:6.5 50PAIRS\/BOX REF:1LSPF-1165",
            "Generic Name":null,
            "Manufacturer":"MEDISMART",
            "Purchase Unit":"BOX",
            "Purchase Price":40,
            "Units Per Pack":50,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":7,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00007",
            "Item Name":"GLOVES MEDISMART STERILE SURGICAL  SIZE:7.0 50PAIRS\/BOX REF:1LSPF-1170",
            "Generic Name":null,
            "Manufacturer":"MEDISMART",
            "Purchase Unit":"BOX",
            "Purchase Price":40,
            "Units Per Pack":50,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":8,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00008",
            "Item Name":"GLOVES MEDISMART STERILE SURGICAL  SIZE:7.5 50PAIRS\/BOX REF:1LSPF-1175",
            "Generic Name":null,
            "Manufacturer":"MEDISMART",
            "Purchase Unit":"BOX",
            "Purchase Price":40,
            "Units Per Pack":50,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":9,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00009",
            "Item Name":"GLOVES MEDISMART STERILE SURGICAL  SIZE:8.0 50PAIRS\/BOX REF:1LSPF-1180",
            "Generic Name":null,
            "Manufacturer":"MEDISMART",
            "Purchase Unit":"BOX",
            "Purchase Price":40,
            "Units Per Pack":50,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":10,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00010",
            "Item Name":"GLOVES MEDISMART STERILE SURGICAL  SIZE:6.0 50PAIRS\/BOX REF:1LSPF-1160",
            "Generic Name":null,
            "Manufacturer":"MEDISMART",
            "Purchase Unit":"BOX",
            "Purchase Price":40,
            "Units Per Pack":50,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":11,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00011",
            "Item Name":"MEDICAL PROFESSIONAL CLIPPERS WITH MEDICAL CHARGING STATION",
            "Generic Name":null,
            "Manufacturer":null,
            "Purchase Unit":"PCS",
            "Purchase Price":375,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":0,
            "Salable":"N"
        },
        {
            "Sl No.":12,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00012",
            "Item Name":"MEDICAL PROFESSIONAL CLIPPER REF:SCOO3 25\/BOX",
            "Generic Name":null,
            "Manufacturer":null,
            "Purchase Unit":"PCS",
            "Purchase Price":8.7,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":17,
            "Salable":"Y"
        },
        {
            "Sl No.":13,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00013",
            "Item Name":"MEDICAL PROFESSIONAL CLIPPER REF:SCOO2 25\/BOX",
            "Generic Name":null,
            "Manufacturer":null,
            "Purchase Unit":"PCS",
            "Purchase Price":8.2,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":16,
            "Salable":"Y"
        },
        {
            "Sl No.":14,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00014",
            "Item Name":"OXYGEN NASAL CANNULA ADULT MICROTECH REF:GM-001-003A",
            "Generic Name":null,
            "Manufacturer":"MICROTECH",
            "Purchase Unit":"PCS",
            "Purchase Price":1.2,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":15,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00015",
            "Item Name":"OXYGEN NASAL CANNULA ADULT MICROTECH REF:GM-001-003A",
            "Generic Name":null,
            "Manufacturer":"MICROTECH",
            "Purchase Unit":"PCS",
            "Purchase Price":1.2,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":16,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00016",
            "Item Name":"MASK NEBULIZER  ADULT REF:A0201",
            "Generic Name":null,
            "Manufacturer":"SOUNDWAY",
            "Purchase Unit":"PCS",
            "Purchase Price":2.5,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":5,
            "Salable":"Y"
        },
        {
            "Sl No.":17,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00017",
            "Item Name":"SAFESPLINT 36INCH REF:900672 SAFECARE",
            "Generic Name":null,
            "Manufacturer":"SAFECARE MEDICAL",
            "Purchase Unit":"PCS",
            "Purchase Price":40,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":18,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00018",
            "Item Name":" IV ADMINISTRATION SET BROMED REF:IVIN-20",
            "Generic Name":null,
            "Manufacturer":"BROMED",
            "Purchase Unit":"PCS",
            "Purchase Price":0.75,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
        {
            "Sl No.":19,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00019",
            "Item Name":"IV ADMINISTRATION SET MEDISOFT REF:IVIY-E",
            "Generic Name":null,
            "Manufacturer":"MEDISOFT",
            "Purchase Unit":"PCS",
            "Purchase Price":0.6,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":1,
            "Salable":"Y"
        },
        {
            "Sl No.":20,
            "Category":"CONSUMABLES",
            "Sub Category":"MEDICAL CONSUMABLE",
            "Item Code":"IMC-00020",
            "Item Name":" INFUSION SET MICROTECH REF:111073",
            "Generic Name":null,
            "Manufacturer":"MICROTECH",
            "Purchase Unit":"PCS",
            "Purchase Price":1,
            "Units Per Pack":1,
            "Sale Unit":"PCS",
            "Sale Price":2,
            "Salable":"Y"
        },
     
    ]
  return (
   <></>
  )
}

export default MedicalsItems