import { getNames } from "country-list";

export const DropdownOptions = {
  visitOptions: [
    // { id: "1", label: "Emergency Room", value: "emergency_room" },
    // { id: "2", label: "Surgery Room", value: "surgery" },
    // { id: "3", label: "Physio Room", value: "physio_room" },
    // { id: "4", label: "Non Consultation", value: "non_consultation" },
    // { id: "5", label: "Tele Medicine", value: "tele_medicine" },
    { id: "6", label: "In Patient", value: "ip" },
    { id: "7", label: "Out Patient", value: "op" },
  ],
  genderOpton: [
    { label: "Select", value: "" },
    { label: "Female", value: "female" },
    { label: "Male", value: "male" },
    { label: "Other", value: "other" },
  ],
  nationalityOptions: getNames().map((name) => ({
    value: name.toLowerCase(),
    label: name,
  })),
  visaTypeOptions: [
    { id: "1", label: "Local", value: "local" },
    { id: "2", label: "Resident", value: "resident" },
    { id: "3", label: "Visitor", value: "visitor" },
  ],
  specialityOptions: [
    { id: "1", label: "speciality 1", value: "speciality_1" },
    { id: "2", label: "speciality 2", value: "speciality_2" },
  ],
  encounterTypeOptions: [
    {
      id: "1",
      label: "No Bed + No Emergency Room",
      value: "no_bed_no_emergency_room",
    },
    {
      id: "2",
      label: "No Bed + Emergency Room",
      value: "no_bed_emergency_room",
    },
    {
      id: "3",
      label: "Daycase Bed + No Emergency Room",
      value: "daycase_bed_no_emergency_room",
    },
    {
      id: "4",
      label: "Daycase Bed + Emergency Room",
      value: "daycase_bed_emergency_room",
    },
  ],
  ipEncounterTypeOptions: [
    {
      id: "1",
      label: "daycase bed + emergency  ",
      value: "daycase_emergency_room",
    },
    // {
    //   id: "2",
    //   label: "No Bed + Emergency Room",
    //   value: "no_bed_emergency_room",
    // },
    // {
    //   id: "3",
    //   label: "Daycase Bed + No Emergency Room",
    //   value: "daycase_bed_no_emergency_room",
    // },
    // {
    //   id: "4",
    //   label: "Daycase Bed + Emergency Room",
    //   value: "daycase_bed_emergency_room",
    // },
  ],
  doctorOptions: [
    { id: "1", label: "Doctor 1", value: "doctor_1" },
    { id: "2", label: "Doctor 2", value: "doctor_2" },
  ],
  paymentOptions: [
    {
      id: "1",
      label: "Cash",
      value: "cash",
    },
    {
      id: "2",
      label: "Insurance",
      value: "insurance",
    },
    {
      id: "3",
      label: "Corporate",
      value: "corporate",
    },
  ],
  infoSourceOptions: [
    { id: "1", label: "Event", value: "event" },
    { id: "2", label: "Family and Friends", value: "family_and_friends" },
    { id: "3", label: "Fazaa", value: "fazaa" },
    { id: "4", label: "Google", value: "google" },
    { id: "5", label: "My Alfred App", value: "my_alfred_app" },
    { id: "6", label: "Promotions", value: "promotion" },
    { id: "7", label: "Social Media", value: "social_media" },
    { id: "8", label: "Website", value: "website" },
  ],
  patientTypeOptions: [
    { id: "1", label: "Normal", value: "normal" },
    { id: "2", label: "Recruitment", value: "recruitment" },
    { id: "3", label: "Pre-Employment", value: "pre-employment" },
    { id: "4", label: "VIP", value: "vip" },
    { id: "5", label: "VVIP", value: "vvip" },
    { id: "6", label: "Determination", value: "determination" },
  ],
  otherIdOptions: [
    { id: "1", label: "Passport", value: "passport" },
    { id: "2", label: "GCC ID", value: "gcc_id" },
    { id: "3", label: "Driving License", value: "driving_license" },
  ],
  addressOptions: [
    { id: "1", label: "Dubai", value: "Dubai" },
    { id: "2", label: "Abu Dhabi", value: "Abu Dhabi" },
    { id: "3", label: "Sharjah", value: "Sharjah" },
    { id: "4", label: "Fujairah", value: "Fujairah" },
    { id: "5", label: "Ras Al Khaimah", value: "Ras Al Khaimah" },
    { id: "6", label: "Umm Al Quwain", value: "Umm Al Quwain" },
    { id: "7", label: "Ajman", value: "Ajman" },
    { id: "8", label: "Others", value: "Others" },
    { id: "9", label: "Unknown", value: "Unknown" },
  ],
  referralOptions: [
    { id: "1", label: "Yes", value: "yes" },
    { id: "2", label: "No", value: "no" },
  ],
  religionOptions: [
    { id: "1", label: "Buddhist", value: "BUD" },
    { id: "2", label: "Buddhist: Mahayana", value: "BMA" },
    { id: "3", label: "Buddhist: Theravada", value: "BTH" },
    { id: "4", label: "Christian", value: "CHR" },
    { id: "5", label: "Christian: Anglican", value: "ANG" },
    { id: "6", label: "Christian: Baptist", value: "BAP" },
    { id: "7", label: "Christian: Christian Science", value: "CHS" },
    { id: "8", label: "Christian: Episcopalian", value: "EPI" },
    { id: "9", label: "Christian: Greek Orthodox", value: "GRE" },
    { id: "10", label: "Christian: Jehovah's Witness", value: "JWN" },
    { id: "11", label: "Christian: Lutheran", value: "LUT" },
    { id: "12", label: "Christian: Mennonite", value: "MEN" },
    { id: "13", label: "Christian: Methodist", value: "MET" },
    { id: "14", label: "Christian: Pentecostal", value: "PEN" },
    { id: "15", label: "Christian: Presbyterian", value: "PRE" },
    { id: "16", label: "Christian: Protestant", value: "PRO" },
    { id: "17", label: "Christian: Roman Catholic", value: "CAT" },
    { id: "18", label: "Christian: Seventh Day Adventist", value: "SEV" },
    { id: "19", label: "Christian: Unitarian Universalist", value: "UNU" },
    { id: "20", label: "Ethnic Religionist", value: "ERL" },
    { id: "21", label: "Hindu", value: "HIN" },
    { id: "22", label: "Hindu: Other", value: "HOT" },
    { id: "23", label: "Jain", value: "JAI" },
    { id: "24", label: "Jewish", value: "JEW" },
    { id: "25", label: "Muslim", value: "MOS" },
    { id: "26", label: "Muslim: Other", value: "MOT" },
    { id: "27", label: "Muslim: Shiite", value: "MSH" },
    { id: "28", label: "Muslim: Sunni", value: "MSU" },
    { id: "29", label: "Other", value: "OTH" },
    { id: "30", label: "Sikh", value: "SIK" },
    { id: "31", label: "Shintoist", value: "SHN" },
    { id: "32", label: "Unknown", value: "VAR" },
  ],
  patientPriorityOptions: [
    { id: "1", label: "Normal", value: "normal" },
    { id: "2", label: "VIP", value: "vip" },
    { id: "3", label: "VVIP", value: "vvip" },
  ],
  maritalStatusOptions: [
    { id: "1", label: "Annulled", value: "annulled" },
    { id: "2", label: "Divorced", value: "divorced" },
    { id: "3", label: "Legally Married", value: "legally_married" },
    { id: "4", label: "Married", value: "married" },
    { id: "5", label: "Other", value: "other" },
    { id: "6", label: "Separated", value: "separated" },
    { id: "7", label: "Single", value: "single" },
    { id: "8", label: "Unknown", value: "unknown" },
    { id: "9", label: "Widowed", value: "widowed" },
    { id: "10", label: "Unmarried", value: "unmarried" },
  ],
  occupationOptions: [
    { value: "", label: "--Please choose an option--" },
    { value: "agriculture", label: "Agriculture" },
    { value: "airlines", label: "Airlines" },
    { value: "healthcare", label: "Healthcare and medicine" },
    { value: "arts", label: "Arts and entertainment" },
    { value: "banking", label: "Banking and Finance" },
    { value: "blue_collar", label: "Blue Collar" },
    { value: "business", label: "Business" },
    { value: "consultant", label: "Consultant" },
    { value: "industrial", label: "Industrial and manufacturing" },
    { value: "home_maker", label: "Home Maker" },
    { value: "hospitality", label: "Hospitality" },
    { value: "it_professional", label: "IT Professional" },
    { value: "law_enforcement", label: "Law enforcement and armed forces" },
    { value: "lawyer", label: "Lawyer" },
    { value: "media", label: "Media" },
    { value: "mining", label: "Mining" },
    { value: "other", label: "Other" },
    { value: "research", label: "Research" },
    { value: "retired", label: "Retired" },
    { value: "road_transport", label: "Road Transport" },
    { value: "science_technology", label: "Science and technology" },
    { value: "shipping", label: "Shipping" },
    { value: "skilled_labor", label: "Skilled Labor" },
    { value: "sports", label: "Sports" },
    { value: "student", label: "Student" },
    { value: "teacher", label: "Teacher" },
    { value: "unknown", label: "Unknown" },
  ],
};
