export const API_ENDPOINTS = {
  LOGIN: "auth/signin",
  ALL_BRANCH: "admin/getAllBranches",
  ALL_APPOINTMENT: "doctorappointment/getAllAppointments",
  All_DOCTORS: "doctor/getAllDoctors",
  ALL_FACILITIES: "facility/getAllFacilitiesByBranchAndDate",
  DOC_AVAILABLE: "timeslot/getAvailableSlotsForAllDoctors",
  FACILITY_SCHEDULES: "facility/getAllFacilitySchedules",
  FACILITY_AVAILABLE: "timeslot/getAvailableSlotsForAllFacilities",
  SEARCH_DOCTOR: "doctor/searchDoctors",
  SEARCH_FACILITY: "facility/searchFacilities",
  SEARCH_PATIENT: "patient/searchPatients",
  REGISTER_PATIENT: "patient/patientRegistration",
  REVISIT_PATIENT: "patient/patientRevisit",
  EMERGENCY_PATIENT: "patient/patientEmergency",
  BOOK_APPOINTMENT: "doctorappointment/bookAppointment",
  SCHEDULE_LIST: "doctorappointment/getScheduleList",
  RE_SCHEDULE: "doctorappointment/rescheduleAppointment",
  CANCEL_SCHEDULE: "doctorappointment/cancelAppointment",
  PATIENT_LIST : "patient/today"
};
